AllCops:
  Exclude:
    - bin/console
    - bin/setup
    - lib/intellimesh/config/sneakers_extensions.rb

Gemspec/OrderedDependencies:
  Exclude:
    - intellimesh.gemspec

Layout/IndentHeredoc:
  Exclude:
    - lib/intellimesh/generators/sneakers_active_job_host_generator.rb

Metrics/BlockLength:
  Exclude:
    - spec/intellimesh/configuration/diplomat_provider_spec.rb

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Style/BracesAroundHashParameters:
  Enabled: false

Style/Documentation:
  Exclude:
    - lib/intellimesh.rb
    - lib/intellimesh/configuration.rb
    - lib/intellimesh/generators.rb
    - lib/intellimesh/process_host.rb
    - lib/intellimesh/protocols.rb
    - lib/intellimesh/protocols/amqp.rb
    - lib/intellimesh/process_host/configuration.rb

Style/ExpandPathArguments:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/StringLiterals:
  Enabled: false